// Generated from the approved 306-icon review (Fluent Emoji 3D). Edit by
// hand, then run `python3 tool/emoji/fetch.py` to bundle new art.

/// 00.20 EmojiSheet chips, in display order.
enum EmojiGroup {
  makan,
  jalan,
  rumah,
  belanja,
  hiburan,
  hewan,
  duit,
  sehat,
  sekolah,
  kerja,
  sosial,
}

/// One pickable icon: [emoji] is what gets stored (unicode, not a file).
typedef CatalogEmoji = ({
  String emoji,
  EmojiGroup group,
  List<String> keywords,
});

/// The only icons mibu shows: every emoji in the app comes from here.
const emojiCatalog = <CatalogEmoji>[
  // makan
  (
    emoji: '☕',
    group: EmojiGroup.makan,
    keywords: ['kopi', 'ngopi', 'kafe', 'coffee'],
  ),
  (emoji: '🍵', group: EmojiGroup.makan, keywords: ['teh', 'ngeteh']),
  (
    emoji: '🧋',
    group: EmojiGroup.makan,
    keywords: ['boba', 'es', 'teh', 'susu', 'thai', 'tea'],
  ),
  (
    emoji: '🥤',
    group: EmojiGroup.makan,
    keywords: ['minuman', 'es', 'jus', 'soda'],
  ),
  (
    emoji: '🧃',
    group: EmojiGroup.makan,
    keywords: ['jus', 'kotak', 'susu', 'kotak'],
  ),
  (emoji: '🥛', group: EmojiGroup.makan, keywords: ['susu']),
  (emoji: '🍼', group: EmojiGroup.makan, keywords: ['susu', 'bayi', 'dot']),
  (emoji: '🍺', group: EmojiGroup.makan, keywords: ['bir']),
  (emoji: '🍷', group: EmojiGroup.makan, keywords: ['wine']),
  (
    emoji: '🍹',
    group: EmojiGroup.makan,
    keywords: ['es', 'kelapa', 'minuman', 'segar', 'mocktail'],
  ),
  (emoji: '🧊', group: EmojiGroup.makan, keywords: ['es', 'batu']),
  (emoji: '🥥', group: EmojiGroup.makan, keywords: ['kelapa']),
  (emoji: '🍚', group: EmojiGroup.makan, keywords: ['nasi']),
  (
    emoji: '🍛',
    group: EmojiGroup.makan,
    keywords: ['nasi', 'padang', 'kari', 'warteg'],
  ),
  (
    emoji: '🍜',
    group: EmojiGroup.makan,
    keywords: ['mie', 'bakso', 'soto', 'ramen', 'makan'],
  ),
  (emoji: '🍲', group: EmojiGroup.makan, keywords: ['sop', 'sayur', 'kuah']),
  (
    emoji: '🥘',
    group: EmojiGroup.makan,
    keywords: ['rendang', 'gulai', 'masakan'],
  ),
  (emoji: '🍳', group: EmojiGroup.makan, keywords: ['masak', 'telur', 'dapur']),
  (emoji: '🥚', group: EmojiGroup.makan, keywords: ['telur']),
  (
    emoji: '🍗',
    group: EmojiGroup.makan,
    keywords: ['ayam', 'goreng', 'ayam', 'geprek'],
  ),
  (emoji: '🍢', group: EmojiGroup.makan, keywords: ['sate']),
  (emoji: '🍡', group: EmojiGroup.makan, keywords: ['cilok', 'jajanan']),
  (emoji: '🍖', group: EmojiGroup.makan, keywords: ['daging', 'iga']),
  (emoji: '🥩', group: EmojiGroup.makan, keywords: ['daging', 'steak']),
  (
    emoji: '🍤',
    group: EmojiGroup.makan,
    keywords: ['udang', 'gorengan', 'tempura'],
  ),
  (emoji: '🍣', group: EmojiGroup.makan, keywords: ['sushi']),
  (
    emoji: '🍱',
    group: EmojiGroup.makan,
    keywords: ['nasi', 'kotak', 'catering', 'bento'],
  ),
  (emoji: '🥡', group: EmojiGroup.makan, keywords: ['bungkus', 'takeaway']),
  (
    emoji: '🥟',
    group: EmojiGroup.makan,
    keywords: ['dimsum', 'pangsit', 'siomay'],
  ),
  (emoji: '🍙', group: EmojiGroup.makan, keywords: ['onigiri']),
  (emoji: '🍝', group: EmojiGroup.makan, keywords: ['pasta', 'spageti']),
  (emoji: '🍕', group: EmojiGroup.makan, keywords: ['pizza']),
  (emoji: '🍔', group: EmojiGroup.makan, keywords: ['burger']),
  (emoji: '🍟', group: EmojiGroup.makan, keywords: ['kentang', 'goreng']),
  (emoji: '🌭', group: EmojiGroup.makan, keywords: ['hotdog', 'sosis']),
  (
    emoji: '🥪',
    group: EmojiGroup.makan,
    keywords: ['roti', 'lapis', 'sandwich'],
  ),
  (emoji: '🍞', group: EmojiGroup.makan, keywords: ['roti']),
  (
    emoji: '🥐',
    group: EmojiGroup.makan,
    keywords: ['croissant', 'pastry', 'bakery'],
  ),
  (emoji: '🧇', group: EmojiGroup.makan, keywords: ['wafel']),
  (
    emoji: '🥞',
    group: EmojiGroup.makan,
    keywords: ['pancake', 'martabak', 'terang', 'bulan'],
  ),
  (emoji: '🍩', group: EmojiGroup.makan, keywords: ['donat']),
  (
    emoji: '🍪',
    group: EmojiGroup.makan,
    keywords: ['kue', 'cookies', 'biskuit'],
  ),
  (emoji: '🍰', group: EmojiGroup.makan, keywords: ['kue', 'cake']),
  (
    emoji: '🎂',
    group: EmojiGroup.makan,
    keywords: ['kue', 'ultah', 'ulang', 'tahun'],
  ),
  (emoji: '🧁', group: EmojiGroup.makan, keywords: ['cupcake']),
  (emoji: '🍫', group: EmojiGroup.makan, keywords: ['coklat']),
  (emoji: '🍬', group: EmojiGroup.makan, keywords: ['permen']),
  (emoji: '🍦', group: EmojiGroup.makan, keywords: ['es', 'krim']),
  (
    emoji: '🍧',
    group: EmojiGroup.makan,
    keywords: ['es', 'campur', 'es', 'serut'],
  ),
  (emoji: '🍿', group: EmojiGroup.makan, keywords: ['popcorn']),
  (emoji: '🥜', group: EmojiGroup.makan, keywords: ['kacang']),
  (emoji: '🍠', group: EmojiGroup.makan, keywords: ['ubi']),
  (emoji: '🌽', group: EmojiGroup.makan, keywords: ['jagung']),
  (emoji: '🥗', group: EmojiGroup.makan, keywords: ['salad', 'diet']),
  (emoji: '🥦', group: EmojiGroup.makan, keywords: ['sayur', 'brokoli']),
  (emoji: '🥕', group: EmojiGroup.makan, keywords: ['wortel']),
  (emoji: '🍅', group: EmojiGroup.makan, keywords: ['tomat']),
  (emoji: '🌶️', group: EmojiGroup.makan, keywords: ['cabai', 'sambal']),
  (emoji: '🧄', group: EmojiGroup.makan, keywords: ['bawang']),
  (emoji: '🥔', group: EmojiGroup.makan, keywords: ['kentang']),
  (emoji: '🍄', group: EmojiGroup.makan, keywords: ['jamur']),
  (emoji: '🍌', group: EmojiGroup.makan, keywords: ['pisang']),
  (emoji: '🍎', group: EmojiGroup.makan, keywords: ['apel', 'buah']),
  (emoji: '🍊', group: EmojiGroup.makan, keywords: ['jeruk']),
  (emoji: '🍉', group: EmojiGroup.makan, keywords: ['semangka']),
  (emoji: '🥭', group: EmojiGroup.makan, keywords: ['mangga']),
  (emoji: '🍓', group: EmojiGroup.makan, keywords: ['stroberi']),
  (emoji: '🥑', group: EmojiGroup.makan, keywords: ['alpukat']),
  (emoji: '🦐', group: EmojiGroup.makan, keywords: ['udang', 'seafood']),
  (emoji: '🦀', group: EmojiGroup.makan, keywords: ['kepiting', 'seafood']),
  (emoji: '🦑', group: EmojiGroup.makan, keywords: ['cumi']),
  (emoji: '🧂', group: EmojiGroup.makan, keywords: ['garam', 'bumbu', 'dapur']),
  (emoji: '🍯', group: EmojiGroup.makan, keywords: ['madu']),
  (emoji: '🥫', group: EmojiGroup.makan, keywords: ['makanan', 'kaleng']),
  (emoji: '🫙', group: EmojiGroup.makan, keywords: ['toples', 'stok']),
  (
    emoji: '🥣',
    group: EmojiGroup.makan,
    keywords: ['bubur', 'sereal', 'sarapan'],
  ),
  (
    emoji: '🍽️',
    group: EmojiGroup.makan,
    keywords: ['resto', 'restoran', 'makan', 'malam'],
  ),
  (emoji: '🥢', group: EmojiGroup.makan, keywords: ['sumpit']),
  // jalan
  (
    emoji: '🛵',
    group: EmojiGroup.jalan,
    keywords: ['ojol', 'motor', 'gojek', 'grab'],
  ),
  (emoji: '🏍️', group: EmojiGroup.jalan, keywords: ['motor']),
  (emoji: '🚗', group: EmojiGroup.jalan, keywords: ['mobil']),
  (emoji: '🚕', group: EmojiGroup.jalan, keywords: ['taksi']),
  (emoji: '🚙', group: EmojiGroup.jalan, keywords: ['mobil', 'suv']),
  (emoji: '🛺', group: EmojiGroup.jalan, keywords: ['bajaj']),
  (emoji: '🚌', group: EmojiGroup.jalan, keywords: ['bus', 'transjakarta']),
  (emoji: '🚐', group: EmojiGroup.jalan, keywords: ['travel', 'shuttle']),
  (
    emoji: '🚆',
    group: EmojiGroup.jalan,
    keywords: ['kereta', 'krl', 'commuter'],
  ),
  (emoji: '🚇', group: EmojiGroup.jalan, keywords: ['mrt']),
  (emoji: '🚈', group: EmojiGroup.jalan, keywords: ['lrt']),
  (
    emoji: '🚄',
    group: EmojiGroup.jalan,
    keywords: ['kereta', 'cepat', 'whoosh'],
  ),
  (emoji: '🚉', group: EmojiGroup.jalan, keywords: ['stasiun']),
  (
    emoji: '✈️',
    group: EmojiGroup.jalan,
    keywords: ['pesawat', 'tiket', 'pesawat', 'terbang'],
  ),
  (emoji: '🛫', group: EmojiGroup.jalan, keywords: ['berangkat', 'bandara']),
  (emoji: '🚢', group: EmojiGroup.jalan, keywords: ['kapal']),
  (emoji: '⛴️', group: EmojiGroup.jalan, keywords: ['ferry', 'kapal', 'laut']),
  (emoji: '🚲', group: EmojiGroup.jalan, keywords: ['sepeda']),
  (emoji: '🛴', group: EmojiGroup.jalan, keywords: ['skuter']),
  (
    emoji: '⛽',
    group: EmojiGroup.jalan,
    keywords: ['bensin', 'bbm', 'pertalite'],
  ),
  (emoji: '🅿️', group: EmojiGroup.jalan, keywords: ['parkir']),
  (emoji: '🛞', group: EmojiGroup.jalan, keywords: ['ban', 'bengkel']),
  (emoji: '🛣️', group: EmojiGroup.jalan, keywords: ['tol']),
  (emoji: '🚦', group: EmojiGroup.jalan, keywords: ['lampu', 'merah']),
  (emoji: '🧳', group: EmojiGroup.jalan, keywords: ['koper', 'liburan']),
  (emoji: '🏝️', group: EmojiGroup.jalan, keywords: ['pulau', 'liburan']),
  (emoji: '🏖️', group: EmojiGroup.jalan, keywords: ['pantai']),
  (emoji: '🏨', group: EmojiGroup.jalan, keywords: ['hotel', 'penginapan']),
  (emoji: '🏕️', group: EmojiGroup.jalan, keywords: ['camping', 'kemah']),
  (emoji: '⛰️', group: EmojiGroup.jalan, keywords: ['gunung', 'hiking']),
  (
    emoji: '🗺️',
    group: EmojiGroup.jalan,
    keywords: ['peta', 'trip', 'jalan-jalan'],
  ),
  (
    emoji: '🚚',
    group: EmojiGroup.jalan,
    keywords: ['ekspedisi', 'kirim', 'barang', 'pindahan'],
  ),
  // rumah
  (emoji: '🏠', group: EmojiGroup.rumah, keywords: ['rumah']),
  (emoji: '🏡', group: EmojiGroup.rumah, keywords: ['rumah', 'keluarga']),
  (emoji: '🏢', group: EmojiGroup.rumah, keywords: ['kos', 'apartemen']),
  (emoji: '🏘️', group: EmojiGroup.rumah, keywords: ['perumahan', 'kompleks']),
  (
    emoji: '🔑',
    group: EmojiGroup.rumah,
    keywords: ['kunci', 'sewa', 'kontrakan'],
  ),
  (emoji: '🛏️', group: EmojiGroup.rumah, keywords: ['kasur']),
  (emoji: '🛋️', group: EmojiGroup.rumah, keywords: ['sofa', 'furnitur']),
  (emoji: '🪑', group: EmojiGroup.rumah, keywords: ['kursi']),
  (emoji: '🚿', group: EmojiGroup.rumah, keywords: ['mandi']),
  (emoji: '🚽', group: EmojiGroup.rumah, keywords: ['toilet']),
  (emoji: '🧻', group: EmojiGroup.rumah, keywords: ['tisu']),
  (emoji: '🧼', group: EmojiGroup.rumah, keywords: ['sabun']),
  (
    emoji: '🧹',
    group: EmojiGroup.rumah,
    keywords: ['sapu', 'bersih-bersih', 'art'],
  ),
  (emoji: '🧺', group: EmojiGroup.rumah, keywords: ['laundry', 'cucian']),
  (emoji: '🧽', group: EmojiGroup.rumah, keywords: ['spons', 'cuci', 'piring']),
  (emoji: '🪣', group: EmojiGroup.rumah, keywords: ['ember']),
  (
    emoji: '🗑️',
    group: EmojiGroup.rumah,
    keywords: ['sampah', 'iuran', 'sampah'],
  ),
  (emoji: '💡', group: EmojiGroup.rumah, keywords: ['listrik', 'pln', 'token']),
  (emoji: '🔌', group: EmojiGroup.rumah, keywords: ['colokan', 'listrik']),
  (emoji: '💧', group: EmojiGroup.rumah, keywords: ['air', 'pdam', 'galon']),
  (emoji: '🔥', group: EmojiGroup.rumah, keywords: ['gas', 'elpiji']),
  (emoji: '📶', group: EmojiGroup.rumah, keywords: ['internet', 'wifi']),
  (emoji: '📺', group: EmojiGroup.rumah, keywords: ['tv', 'tv', 'kabel']),
  (
    emoji: '🔧',
    group: EmojiGroup.rumah,
    keywords: ['servis', 'perbaikan', 'bengkel'],
  ),
  (emoji: '🔨', group: EmojiGroup.rumah, keywords: ['renovasi', 'tukang']),
  (emoji: '🛠️', group: EmojiGroup.rumah, keywords: ['benerin', 'perkakas']),
  (emoji: '🧰', group: EmojiGroup.rumah, keywords: ['perkakas', 'alat']),
  (emoji: '🪜', group: EmojiGroup.rumah, keywords: ['tangga']),
  (emoji: '🧱', group: EmojiGroup.rumah, keywords: ['bahan', 'bangunan']),
  (emoji: '🪴', group: EmojiGroup.rumah, keywords: ['tanaman']),
  (emoji: '🌱', group: EmojiGroup.rumah, keywords: ['kebun']),
  (emoji: '🔋', group: EmojiGroup.rumah, keywords: ['baterai']),
  (emoji: '🕯️', group: EmojiGroup.rumah, keywords: ['lilin']),
  // belanja
  (
    emoji: '🛒',
    group: EmojiGroup.belanja,
    keywords: ['belanja', 'bulanan', 'supermarket'],
  ),
  (
    emoji: '🛍️',
    group: EmojiGroup.belanja,
    keywords: ['belanja', 'mall', 'shopping'],
  ),
  (
    emoji: '📦',
    group: EmojiGroup.belanja,
    keywords: ['paket', 'online', 'shopee', 'tokopedia'],
  ),
  (
    emoji: '🏪',
    group: EmojiGroup.belanja,
    keywords: ['minimarket', 'indomaret', 'alfamart', 'warung'],
  ),
  (emoji: '🏬', group: EmojiGroup.belanja, keywords: ['mall']),
  (emoji: '🧾', group: EmojiGroup.belanja, keywords: ['struk', 'tagihan']),
  (emoji: '🏷️', group: EmojiGroup.belanja, keywords: ['diskon', 'promo']),
  (emoji: '👕', group: EmojiGroup.belanja, keywords: ['baju', 'kaos']),
  (emoji: '👖', group: EmojiGroup.belanja, keywords: ['celana', 'jeans']),
  (emoji: '👗', group: EmojiGroup.belanja, keywords: ['dress', 'gaun']),
  (emoji: '🧥', group: EmojiGroup.belanja, keywords: ['jaket']),
  (emoji: '👟', group: EmojiGroup.belanja, keywords: ['sepatu', 'sneakers']),
  (emoji: '👠', group: EmojiGroup.belanja, keywords: ['heels']),
  (emoji: '🩴', group: EmojiGroup.belanja, keywords: ['sandal']),
  (emoji: '👜', group: EmojiGroup.belanja, keywords: ['tas']),
  (emoji: '👛', group: EmojiGroup.belanja, keywords: ['dompet']),
  (emoji: '🧢', group: EmojiGroup.belanja, keywords: ['topi']),
  (emoji: '🕶️', group: EmojiGroup.belanja, keywords: ['kacamata', 'hitam']),
  (emoji: '⌚', group: EmojiGroup.belanja, keywords: ['jam', 'tangan']),
  (emoji: '💍', group: EmojiGroup.belanja, keywords: ['cincin', 'perhiasan']),
  (emoji: '💎', group: EmojiGroup.belanja, keywords: ['emas', 'berlian']),
  (emoji: '💄', group: EmojiGroup.belanja, keywords: ['makeup', 'lipstik']),
  (emoji: '💅', group: EmojiGroup.belanja, keywords: ['kuku', 'nail', 'art']),
  (emoji: '🧦', group: EmojiGroup.belanja, keywords: ['kaus', 'kaki']),
  (
    emoji: '📱',
    group: EmojiGroup.belanja,
    keywords: ['hp', 'gadget', 'pulsa', 'paket', 'data'],
  ),
  (emoji: '🧸', group: EmojiGroup.belanja, keywords: ['mainan', 'boneka']),
  (emoji: '🌂', group: EmojiGroup.belanja, keywords: ['payung']),
  // hiburan
  (
    emoji: '🎬',
    group: EmojiGroup.hiburan,
    keywords: ['nonton', 'film', 'bioskop'],
  ),
  (
    emoji: '🎟️',
    group: EmojiGroup.hiburan,
    keywords: ['tiket', 'konser', 'event'],
  ),
  (emoji: '🎤', group: EmojiGroup.hiburan, keywords: ['karaoke']),
  (
    emoji: '🎵',
    group: EmojiGroup.hiburan,
    keywords: ['musik', 'spotify', 'langganan'],
  ),
  (
    emoji: '🎧',
    group: EmojiGroup.hiburan,
    keywords: ['headset', 'musik', 'podcast'],
  ),
  (emoji: '🎸', group: EmojiGroup.hiburan, keywords: ['gitar', 'band']),
  (emoji: '🎹', group: EmojiGroup.hiburan, keywords: ['piano']),
  (emoji: '🥁', group: EmojiGroup.hiburan, keywords: ['drum']),
  (emoji: '🎮', group: EmojiGroup.hiburan, keywords: ['game']),
  (emoji: '🕹️', group: EmojiGroup.hiburan, keywords: ['game', 'arcade']),
  (emoji: '🎲', group: EmojiGroup.hiburan, keywords: ['board', 'game']),
  (emoji: '🧩', group: EmojiGroup.hiburan, keywords: ['puzzle']),
  (emoji: '🎨', group: EmojiGroup.hiburan, keywords: ['seni', 'lukis']),
  (emoji: '📸', group: EmojiGroup.hiburan, keywords: ['foto']),
  (emoji: '📷', group: EmojiGroup.hiburan, keywords: ['kamera']),
  (emoji: '🎭', group: EmojiGroup.hiburan, keywords: ['teater']),
  (
    emoji: '🎡',
    group: EmojiGroup.hiburan,
    keywords: ['taman', 'hiburan', 'dufan'],
  ),
  (emoji: '🎢', group: EmojiGroup.hiburan, keywords: ['wahana']),
  (emoji: '🎳', group: EmojiGroup.hiburan, keywords: ['bowling']),
  (emoji: '🎱', group: EmojiGroup.hiburan, keywords: ['biliar']),
  (
    emoji: '⚽',
    group: EmojiGroup.hiburan,
    keywords: ['futsal', 'sepak', 'bola'],
  ),
  (emoji: '🏀', group: EmojiGroup.hiburan, keywords: ['basket']),
  (emoji: '🏸', group: EmojiGroup.hiburan, keywords: ['badminton']),
  (emoji: '🎾', group: EmojiGroup.hiburan, keywords: ['tenis']),
  (emoji: '🏓', group: EmojiGroup.hiburan, keywords: ['pingpong']),
  (emoji: '🏐', group: EmojiGroup.hiburan, keywords: ['voli']),
  (emoji: '⛳', group: EmojiGroup.hiburan, keywords: ['golf']),
  (emoji: '🎣', group: EmojiGroup.hiburan, keywords: ['mancing']),
  (emoji: '🎉', group: EmojiGroup.hiburan, keywords: ['pesta', 'party']),
  (emoji: '🪩', group: EmojiGroup.hiburan, keywords: ['clubbing']),
  (emoji: '🧶', group: EmojiGroup.hiburan, keywords: ['rajut', 'hobi']),
  (emoji: '🪁', group: EmojiGroup.hiburan, keywords: ['layangan']),
  (emoji: '🏆', group: EmojiGroup.hiburan, keywords: ['lomba']),
  (emoji: '✨', group: EmojiGroup.hiburan, keywords: ['lain-lain', 'lainnya']),
  // hewan
  (emoji: '🐶', group: EmojiGroup.hewan, keywords: ['anjing']),
  (emoji: '🐱', group: EmojiGroup.hewan, keywords: ['kucing']),
  (emoji: '🐈', group: EmojiGroup.hewan, keywords: ['kucing']),
  (emoji: '🐕', group: EmojiGroup.hewan, keywords: ['anjing']),
  (emoji: '🐩', group: EmojiGroup.hewan, keywords: ['grooming']),
  (
    emoji: '🐾',
    group: EmojiGroup.hewan,
    keywords: ['hewan', 'peliharaan', 'petshop', 'anabul'],
  ),
  (emoji: '🦴', group: EmojiGroup.hewan, keywords: ['makanan', 'anjing']),
  (emoji: '🐟', group: EmojiGroup.hewan, keywords: ['ikan']),
  (
    emoji: '🐠',
    group: EmojiGroup.hewan,
    keywords: ['ikan', 'hias', 'akuarium'],
  ),
  (emoji: '🐦', group: EmojiGroup.hewan, keywords: ['burung']),
  (emoji: '🦜', group: EmojiGroup.hewan, keywords: ['burung']),
  (emoji: '🐹', group: EmojiGroup.hewan, keywords: ['hamster']),
  (emoji: '🐰', group: EmojiGroup.hewan, keywords: ['kelinci']),
  (emoji: '🐢', group: EmojiGroup.hewan, keywords: ['kura-kura']),
  (emoji: '🐔', group: EmojiGroup.hewan, keywords: ['ayam']),
  (emoji: '🐄', group: EmojiGroup.hewan, keywords: ['sapi', 'kurban']),
  (emoji: '🐐', group: EmojiGroup.hewan, keywords: ['kambing', 'kurban']),
  // duit
  (emoji: '💰', group: EmojiGroup.duit, keywords: ['gaji', 'gajian', 'uang']),
  (emoji: '💵', group: EmojiGroup.duit, keywords: ['uang', 'tunai', 'cash']),
  (emoji: '💸', group: EmojiGroup.duit, keywords: ['transfer', 'boros']),
  (
    emoji: '💳',
    group: EmojiGroup.duit,
    keywords: ['kartu', 'kredit', 'cicilan', 'paylater'],
  ),
  (emoji: '🪙', group: EmojiGroup.duit, keywords: ['koin', 'receh']),
  (emoji: '🏦', group: EmojiGroup.duit, keywords: ['bank', 'tabungan']),
  (emoji: '🏧', group: EmojiGroup.duit, keywords: ['atm', 'tarik', 'tunai']),
  (emoji: '🐷', group: EmojiGroup.duit, keywords: ['celengan', 'nabung']),
  (
    emoji: '📈',
    group: EmojiGroup.duit,
    keywords: ['investasi', 'saham', 'reksadana'],
  ),
  (emoji: '📉', group: EmojiGroup.duit, keywords: ['rugi']),
  (emoji: '📊', group: EmojiGroup.duit, keywords: ['laporan']),
  (emoji: '🧧', group: EmojiGroup.duit, keywords: ['angpao', 'thr']),
  (
    emoji: '🤝',
    group: EmojiGroup.duit,
    keywords: ['utang', 'piutang', 'pinjam'],
  ),
  (emoji: '🔁', group: EmojiGroup.duit, keywords: ['langganan', 'rutin']),
  (emoji: '🛡️', group: EmojiGroup.duit, keywords: ['asuransi', 'bpjs']),
  (emoji: '🏛️', group: EmojiGroup.duit, keywords: ['pajak']),
  (emoji: '🪪', group: EmojiGroup.duit, keywords: ['ktp', 'dokumen']),
  (emoji: '📒', group: EmojiGroup.duit, keywords: ['buku', 'kas']),
  (emoji: '🧮', group: EmojiGroup.duit, keywords: ['hitung']),
  // sehat
  (emoji: '💊', group: EmojiGroup.sehat, keywords: ['obat', 'apotek']),
  (emoji: '💉', group: EmojiGroup.sehat, keywords: ['vaksin', 'suntik']),
  (emoji: '🩺', group: EmojiGroup.sehat, keywords: ['dokter', 'periksa']),
  (emoji: '🏥', group: EmojiGroup.sehat, keywords: ['rumah', 'sakit']),
  (emoji: '🦷', group: EmojiGroup.sehat, keywords: ['dokter', 'gigi']),
  (emoji: '🩹', group: EmojiGroup.sehat, keywords: ['plester', 'p3k']),
  (emoji: '🌡️', group: EmojiGroup.sehat, keywords: ['demam']),
  (emoji: '😷', group: EmojiGroup.sehat, keywords: ['sakit', 'masker']),
  (emoji: '🧴', group: EmojiGroup.sehat, keywords: ['skincare', 'lotion']),
  (emoji: '💆', group: EmojiGroup.sehat, keywords: ['pijat', 'spa']),
  (
    emoji: '💇',
    group: EmojiGroup.sehat,
    keywords: ['potong', 'rambut', 'salon'],
  ),
  (emoji: '💈', group: EmojiGroup.sehat, keywords: ['barbershop']),
  (emoji: '🏋️', group: EmojiGroup.sehat, keywords: ['gym', 'fitness']),
  (emoji: '🧘', group: EmojiGroup.sehat, keywords: ['yoga']),
  (emoji: '🏃', group: EmojiGroup.sehat, keywords: ['lari', 'olahraga']),
  (emoji: '🚴', group: EmojiGroup.sehat, keywords: ['gowes', 'sepeda']),
  (emoji: '🏊', group: EmojiGroup.sehat, keywords: ['renang']),
  (emoji: '💪', group: EmojiGroup.sehat, keywords: ['olahraga']),
  (emoji: '🩸', group: EmojiGroup.sehat, keywords: ['donor', 'darah']),
  (emoji: '🤰', group: EmojiGroup.sehat, keywords: ['hamil']),
  // sekolah
  (emoji: '📚', group: EmojiGroup.sekolah, keywords: ['buku', 'pelajaran']),
  (emoji: '📖', group: EmojiGroup.sekolah, keywords: ['buku']),
  (emoji: '✏️', group: EmojiGroup.sekolah, keywords: ['alat', 'tulis']),
  (emoji: '🖊️', group: EmojiGroup.sekolah, keywords: ['pulpen']),
  (emoji: '📝', group: EmojiGroup.sekolah, keywords: ['tugas']),
  (emoji: '🎒', group: EmojiGroup.sekolah, keywords: ['tas', 'sekolah']),
  (emoji: '🏫', group: EmojiGroup.sekolah, keywords: ['sekolah', 'spp']),
  (
    emoji: '🎓',
    group: EmojiGroup.sekolah,
    keywords: ['kuliah', 'wisuda', 'ukt'],
  ),
  (
    emoji: '🧑‍🏫',
    group: EmojiGroup.sekolah,
    keywords: ['les', 'guru', 'kursus'],
  ),
  (emoji: '📐', group: EmojiGroup.sekolah, keywords: ['penggaris']),
  (emoji: '🔬', group: EmojiGroup.sekolah, keywords: ['praktikum']),
  (emoji: '🖍️', group: EmojiGroup.sekolah, keywords: ['krayon', 'anak']),
  (emoji: '📓', group: EmojiGroup.sekolah, keywords: ['buku', 'tulis']),
  (emoji: '🖨️', group: EmojiGroup.sekolah, keywords: ['print', 'fotokopi']),
  // kerja
  (emoji: '💼', group: EmojiGroup.kerja, keywords: ['kerja', 'kantor']),
  (emoji: '💻', group: EmojiGroup.kerja, keywords: ['laptop']),
  (emoji: '🖥️', group: EmojiGroup.kerja, keywords: ['komputer']),
  (emoji: '🧑‍💻', group: EmojiGroup.kerja, keywords: ['freelance']),
  (emoji: '👷', group: EmojiGroup.kerja, keywords: ['proyek']),
  (emoji: '📁', group: EmojiGroup.kerja, keywords: ['dokumen']),
  (emoji: '📎', group: EmojiGroup.kerja, keywords: ['atk']),
  (emoji: '📅', group: EmojiGroup.kerja, keywords: ['meeting', 'jadwal']),
  (emoji: '📧', group: EmojiGroup.kerja, keywords: ['email']),
  (emoji: '☎️', group: EmojiGroup.kerja, keywords: ['telepon']),
  (emoji: '👔', group: EmojiGroup.kerja, keywords: ['kerja', 'formal']),
  // sosial
  (emoji: '🎁', group: EmojiGroup.sosial, keywords: ['kado', 'hadiah']),
  (emoji: '🎀', group: EmojiGroup.sosial, keywords: ['kado']),
  (emoji: '💐', group: EmojiGroup.sosial, keywords: ['bunga']),
  (emoji: '🌹', group: EmojiGroup.sosial, keywords: ['bunga', 'pacar']),
  (emoji: '❤️', group: EmojiGroup.sosial, keywords: ['pacar', 'date']),
  (emoji: '💕', group: EmojiGroup.sosial, keywords: ['pacaran']),
  (emoji: '💝', group: EmojiGroup.sosial, keywords: ['hadiah', 'pasangan']),
  (emoji: '💒', group: EmojiGroup.sosial, keywords: ['nikahan', 'kondangan']),
  (emoji: '✉️', group: EmojiGroup.sosial, keywords: ['amplop', 'kondangan']),
  (
    emoji: '🤲',
    group: EmojiGroup.sosial,
    keywords: ['sedekah', 'zakat', 'infak'],
  ),
  (emoji: '🙏', group: EmojiGroup.sosial, keywords: ['doa']),
  (emoji: '🕌', group: EmojiGroup.sosial, keywords: ['masjid', 'ibadah']),
  (emoji: '⛪', group: EmojiGroup.sosial, keywords: ['gereja']),
  (emoji: '🛕', group: EmojiGroup.sosial, keywords: ['pura']),
  (emoji: '📿', group: EmojiGroup.sosial, keywords: ['tasbih']),
  (
    emoji: '🌙',
    group: EmojiGroup.sosial,
    keywords: ['ramadan', 'lebaran', 'puasa'],
  ),
  (emoji: '🎄', group: EmojiGroup.sosial, keywords: ['natal']),
  (emoji: '🏮', group: EmojiGroup.sosial, keywords: ['imlek']),
  (emoji: '🎈', group: EmojiGroup.sosial, keywords: ['ultah', 'balon']),
  (emoji: '👶', group: EmojiGroup.sosial, keywords: ['bayi', 'popok']),
  (emoji: '🫶', group: EmojiGroup.sosial, keywords: ['teman', 'nongkrong']),
];

/// Shown for a stored emoji the catalog doesn't have (data from before the
/// catalog): never the phone's own emoji font.
const fallbackEmoji = '🫙';

String _norm(String e) => e.replaceAll('\u{FE0F}', '');

final _inCatalog = {for (final c in emojiCatalog) _norm(c.emoji)};

/// [emoji] if the catalog has it, else [fallbackEmoji].
String catalogEmoji(String emoji) =>
    _inCatalog.contains(_norm(emoji)) ? emoji : fallbackEmoji;
